### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by exic** [mskcc/roslin-variants#341]
Hi & thanks for making this open source!

I'm trying to get roslin-variant running, but I can't find the example directory mentioned in this section: https://github.com/mskcc/roslin-variant#test-an-example

Any hints on how to find out more about it to make it easier for me to adapt it? Would it be safe to try the old examples which were deleted in 43b7af9c (probably there was a reason to remove them)?

We've been running https://github.com/mskcc/Innovation-IMPACT-Pipeline before but wanted to switch now, since the other one didn't see much activity.

[Edit] So, I randomly tried to run the example from `setup/examples/Variant_calling` now, which runs `roslin_request_to_yaml.py` but complains about missing unset ROSLIN_PIPELINE_BIN_PATH. However that seems to be resolved after setting ROSLIN_PIPELINE_NAME and ROSLIN_PIPELINE_VERSION, now I need to find out why it complains about missing "toil" module.. :-)

**Comment by exic** [comment]
The reason why I didn't see test data/examples might be because something broke while running `build-pipeline.sh`:
```
2020-03-20 15:24:00,161 - Downloading test data
Traceback (most recent call last):
  File "/home/j/quantiom/item/roslin/roslin-core/2.2.1/bin/roslin_create_test_files.py", line 130, in <module>
    main()
  File "/home/j/quantiom/item/roslin/roslin-core/2.2.1/bin/roslin_create_test_files.py", line 126, in main
    create_test_data(pipeline_settings,test_settings)
  File "/home/j/quantiom/item/roslin/roslin-core/2.2.1/bin/roslin_create_test_files.py", line 78, in create_test_data
    download_test_data(test_data_path,test_data_url,test_data_archive)
  File "/home/j/quantiom/item/roslin/roslin-core/2.2.1/bin/roslin_create_test_files.py", line 49, in download_test_data
    test_data_tar.write(chunk)
TypeError: write() argument must be str, not bytes
```

**Comment by exic** [comment]
Looking to fix this, I found this has already been patched here: https://github.com/mskcc/roslin-core/commit/82c55fa053b95dfedf0a966b28d35386c2e1a28a

I guess I'll just update the core reference in my copy and go with that. You'll probably update soon anyways, so I'll close this issue :smiley:
